server:
  port: 9001
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/security-db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    loginType: JSON


mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
logging:
  level:
    org:
      springframework:
        web: debug
        security: debug