server:
  port: 8888

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://localhost:3306/security-db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 111111
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    loginType: JSON


mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

jwt:
  secret: ffjaksdfjaklf
  expiration: 3600000
  header: JWTHeaderName